# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-13 08:10
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180410_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=accounts.models.set_profile_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
