# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-10 14:22
from __future__ import unicode_literals

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='static/avatar.jpeg', upload_to=accounts.models.set_image_path),
        ),
    ]
