# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-13 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180412_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo_thumbnail',
            new_name='profile_thumbnail',
        ),
    ]
