# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-13 09:22
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180413_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=post.models.set_post_path, verbose_name='사진'),
        ),
    ]
