# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20180517_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visits',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
