# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visits',
            field=models.IntegerField(blank=True, verbose_name='조회 수'),
        ),
    ]
