# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20180605_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visits',
            field=models.IntegerField(default=1, verbose_name='조회 수'),
        ),
    ]
