# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-13 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=post.models.set_post_path)),
                ('title', models.CharField(help_text='100자 이내로 입력해주세요.', max_length=100, verbose_name='제목')),
                ('content', models.CharField(help_text='150자 이내로 입력해주세요.', max_length=150, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
