# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-19 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('author', 'post')]),
        ),
    ]
