# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20180430_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40, verbose_name='제목'),
        ),
    ]
