branch-defaults:
  default:
    environment: lcwblog
environment-defaults:
  lcwblog:
    branch: null
    repository: null
global:
  application_name: myblog
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.0
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
